-- =============================================================================
-- 0012_create_org_invitations.sql
-- Owner: nexire-data
-- Purpose: Team invitation flow. Owner/admin creates invite; invitee accepts via token.
--          Token policy allows unauthenticated reads (for accept-invite page).
-- Dependencies: 0001
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: org_invitations
-- One row per outstanding invite. accepted_at is NULL until claimed.
-- token is a cryptographically random string generated by the application.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.org_invitations (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,
  email         text NOT NULL,
  role          text NOT NULL DEFAULT 'member'
                  CHECK (role IN ('admin', 'member')),
  token         text UNIQUE NOT NULL,     -- app generates: nanoid(32) or crypto.randomUUID()
  invited_by    uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  accepted_at   timestamptz,              -- NULL = pending; timestamp = accepted
  expires_at    timestamptz,              -- optional expiry (72h recommended)
  created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.org_invitations IS
  'Team invitation records. token is sent in invite email link. '
  'Accept page uses token to look up the invite (no auth required).';
COMMENT ON COLUMN public.org_invitations.token IS
  'Cryptographically random token. Generate with nanoid(32) or crypto.randomUUID() '
  'in application code. Never expose to anyone other than the invitee.';
COMMENT ON COLUMN public.org_invitations.accepted_at IS
  'Null = invite pending. Set to now() when invitee signs in and accepts.';
COMMENT ON COLUMN public.org_invitations.expires_at IS
  'Recommend 72 hours from creation. Check expiry in API before accepting.';

-- ---------------------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------------------
-- Primary accept-invite lookup: /api/auth/accept-invite?token=...
CREATE INDEX IF NOT EXISTS idx_invitations_token
  ON public.org_invitations(token)
  WHERE accepted_at IS NULL;

-- Org management view (pending invites)
CREATE INDEX IF NOT EXISTS idx_invitations_org_pending
  ON public.org_invitations(org_id, accepted_at)
  WHERE accepted_at IS NULL;

-- ---------------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- SPECIAL: unauthenticated users need SELECT by token (invite acceptance page)
-- ---------------------------------------------------------------------------
ALTER TABLE public.org_invitations ENABLE ROW LEVEL SECURITY;

-- PUBLIC: anyone with a valid token can read the invitation (to show accept page)
-- Application code checks: token exists, not accepted, not expired
CREATE POLICY "public_can_read_invite_by_token"
  ON public.org_invitations FOR SELECT
  USING (true);
-- Note: this is intentionally permissive for SELECT — the token itself is the secret.
-- Never return invitation rows in a list without filtering by token or org_id.
-- Application code filters: SELECT ... WHERE token = $token AND accepted_at IS NULL

-- Owner/admin can create invites
CREATE POLICY "owner_admin_can_insert_invitations"
  ON public.org_invitations FOR INSERT
  WITH CHECK (
    org_id IN (
      SELECT org_id FROM public.profiles
      WHERE id = auth.uid() AND member_role IN ('owner', 'admin')
    )
  );

-- Owner/admin can update (e.g. cancel an invite)
CREATE POLICY "owner_admin_can_update_invitations"
  ON public.org_invitations FOR UPDATE
  USING (
    org_id IN (
      SELECT org_id FROM public.profiles
      WHERE id = auth.uid() AND member_role IN ('owner', 'admin')
    )
  );

-- Service role (cron/accept-invite API) updates accepted_at via admin client
-- No additional RLS needed — SUPABASE_SERVICE_ROLE_KEY bypasses RLS.

-- Owner/admin can delete (cancel) invitations
CREATE POLICY "owner_admin_can_delete_invitations"
  ON public.org_invitations FOR DELETE
  USING (
    org_id IN (
      SELECT org_id FROM public.profiles
      WHERE id = auth.uid() AND member_role IN ('owner', 'admin')
    )
  );
