-- Migration: 0018_gemini_vector_index.sql
-- Description: Drop the previous 1536-dimensional OpenAI vector setup and replace it with a 768-dimensional Gemini setup.

-- 1. Drop existing objects that depend on the 1536 dimension size
DROP FUNCTION IF EXISTS match_prospeo_enum(vector(1536), text, float, int);
DROP TABLE IF EXISTS prospeo_embeddings;

-- 2. Ensure pgvector is enabled (should already be, but safe to include)
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

-- 3. Create the new table for Gemini's 768-dimensional embeddings
CREATE TABLE prospeo_embeddings (
    id bigint generated by default as identity primary key,
    category text not null, -- 'technology', 'industry', or 'department'
    label text not null,    -- The exact string required by Prospeo API
    embedding vector(768) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create an index for faster similarity searches (gemini models natively produce normalized vectors, so inner product is fine)
-- We'll use HNSW index for better performance over IVFFlat
CREATE INDEX ON prospeo_embeddings USING hnsw (embedding vector_ip_ops);

-- 5. Create the updated matching RPC function
CREATE OR REPLACE FUNCTION match_prospeo_enum (
  query_embedding vector(768),
  match_category text,
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  category text,
  label text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  return query
  select
    prospeo_embeddings.id,
    prospeo_embeddings.category,
    prospeo_embeddings.label,
    -- Inner product (for normalized vectors) returns a similarity score where 1 is identical.
    -- (embedding <#> query_embedding) actually returns distance where lower is closer, so similarity is (1 - distance)
    1 - (prospeo_embeddings.embedding <#> query_embedding) as similarity
  from prospeo_embeddings
  where prospeo_embeddings.category = match_category
    -- we only want results that are closer than the threshold
    and 1 - (prospeo_embeddings.embedding <#> query_embedding) > match_threshold
  order by prospeo_embeddings.embedding <#> query_embedding
  limit match_count;
END;
$$;
