-- Migration: 0021_fix_vector_search.sql
-- Description: Ensure the match_prospeo_enum function exists and is correct for 768-dim embeddings.

-- 1. Ensure pgvector is enabled
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

-- 2. Create the table if it doesn't exist (preserve data if it does)
CREATE TABLE IF NOT EXISTS prospeo_embeddings (
    id bigint generated by default as identity primary key,
    category text not null, -- 'technology', 'industry', or 'department'
    label text not null,    -- The exact string required by Prospeo API
    embedding vector(768) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create index if it doesn't exist (Postgres doesn't support IF NOT EXISTS for indexes easily in one line, but we can ignore error or just leave it)
-- We'll skip index creation in this safe migration to avoid errors if it exists. 
-- The previous migration 0018 handles index creation.

-- 4. Create or Replace the matching RPC function to ensure it's up to date
CREATE OR REPLACE FUNCTION match_prospeo_enum (
  query_embedding vector(768),
  match_category text,
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  category text,
  label text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  return query
  select
    prospeo_embeddings.id,
    prospeo_embeddings.category,
    prospeo_embeddings.label,
    -- Inner product (for normalized vectors) returns a similarity score where 1 is identical.
    -- (embedding <#> query_embedding) actually returns distance where lower is closer, so similarity is (1 - distance)
    1 - (prospeo_embeddings.embedding <#> query_embedding) as similarity
  from prospeo_embeddings
  where prospeo_embeddings.category = match_category
    -- we only want results that are closer than the threshold
    and 1 - (prospeo_embeddings.embedding <#> query_embedding) > match_threshold
  order by prospeo_embeddings.embedding <#> query_embedding
  limit match_count;
END;
$$;
